name: jobone
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - sync
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.12.0"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "Merge,!Blocked,!Don't merge,!Stacked PR"
          MERGE_REMOVE_LABELS: "Merge"
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "automatic"
          MERGE_FORKS: "false"
          MERGE_RETRIES: "6"
          MERGE_RETRY_SLEEP: "10000"

# name: jobone
# on:
#   workflow_call
# jobs:
#   job_one:
#     runs-on: ubuntu-latest
#     steps:
#       - run: exit 1
