name: jobone
on:
  push
jobs:
  job_one:
    runs-on: ubuntu-latest
    steps:
      - run: echo job ONE done

# name: jobone
# on:
#   workflow_call
# jobs:
#   job_one:
#     runs-on: ubuntu-latest
#     steps:
#       - run: exit 1
