name: "expressions test"
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  testing-job:
    runs-on: ubuntu-latest
    steps:
      - name: expressions
        run: |
          echo "This is a test job"
          echo "The current PR title is ${{ github.event.pull_request.title }}"
          echo "The current PR title toJSON ${{ toJson(github.event.pull_request.title) }}"
          echo "The current PR title fromJSON ${{ fromJson(github.event.pull_request.title) }}"
