name: jobtwo
on:
  workflow_run:
    workflows: ["jobone"]
    types:
      - completed
jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'

# name: jobtwo
# on:
#   push:
#     tags:  # trigger the deploy job on tag creation
#     - *
# jobs:
#   tests:
#     uses: ./.github/workflows/tests.yml  # use the callable tests job to run tests
#   deploy:
#     name: deploy
#     needs: [tests]  # require tests to pass before deploy runs