name: "2nd job"

on:
  workflow_run:
    workflows: ["1st job"]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    steps:
      - name: job number two
        run: |
          echo job TWO done
