name: jobtwo
on:
  pull_request:
    types: [ closed ]
    branches: [ main ]

  workflow_run:
    workflows: [jobone]
    types:
      - completed

jobs:
  one:
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    if: github.event.action == 'closed' && github.event.pull_request.merged == true
    steps:
      - run: echo one

  two:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'closed' && github.event.pull_request.merged == true }}
    steps:
      - run: echo two

  three:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - run: echo three

