name: jobtwo
on:
  pull_request:
    types: [ closed ]
    branches: [ main ]

  workflow_run:
    workflows: ["Automatic merge"]
    types: [ completed ]
    branches: [ main ]

jobs:
  phrase-push:
    runs-on: ubuntu-latest
    if: (github.event_name == 'workflow_run') || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true)
    steps:
      - run: echo phrase-push
