# name: jobtwo
# on:
#   workflow_run:
#     workflows: ["jobone"]
#     types:
#       - completed
# jobs:
#   on-success:
#     runs-on: ubuntu-latest
#     if: ${{ github.event.workflow_run.conclusion == 'success' }}
#     steps:
#       - run: echo 'The triggering workflow passed'
#   on-failure:
#     runs-on: ubuntu-latest
#     if: ${{ github.event.workflow_run.conclusion == 'failure' }}
#     steps:
#       - run: echo 'The triggering workflow failed'

name: jobtwo
on:
  push
jobs:
  tests:
    uses: ./.github/workflows/one.yml  # use the callable tests job to run tests
  job_two:
    name: job_two
    needs: [tests]
    steps:
      - run: echo 'done running two'